Name :- Vanshika Singla

Registration Number :- 21BCE3916

Institution Name :- VIT-Vellore

Slot :- 6:00pm - 8:00pm(Evening)

# **Task 1 -Create pandas dataframe with numpy random values(4 observation and 4 features)**

In [7]:
import numpy as np
import pandas as pd
A=np.random.randint(10,size=(4,4))
A

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7],
       [7, 2, 5, 4]])

In [8]:
df=pd.DataFrame(A)

In [9]:
df

   0  1  2  3
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7
3  7  2  5  4

# Task 2 -Rename the Task1 columns as 'Random value1','Random value2','Random value3','Random value4'

In [10]:
df.columns=['Random value1','Random value2','Random value3','Random value4']
df

   Random value1  Random value2  Random value3  Random value4
0              6              3              7              4
1              6              9              2              6
2              7              4              3              7
3              7              2              5              4

# **Task 3 - Find the descriptive statistic of df DataFrame**

In [13]:
df.describe()

       Random value1  Random value2  Random value3  Random value4
count        4.00000       4.000000       4.000000           4.00
mean         6.50000       4.500000       4.250000           5.25
std          0.57735       3.109126       2.217356           1.50
min          6.00000       2.000000       2.000000           4.00
25%          6.00000       2.750000       2.750000           4.00
50%          6.50000       3.500000       4.000000           5.00
75%          7.00000       5.250000       5.500000           6.25
max          7.00000       9.000000       7.000000           7.00

# **Task 4 - Check the null values in the DataFrame and find the datatypes of the columns**

In [14]:
df.isnull().any()

Random value1    False
Random value2    False
Random value3    False
Random value4    False
dtype: bool

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Random value1  4 non-null      int64
 1   Random value2  4 non-null      int64
 2   Random value3  4 non-null      int64
 3   Random value4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

# **Task 5 - Display the 'Random value2' and 'Random value3' columns with location method and indexlocation method**

In [22]:
df.iloc[:,[1,2]]

   Random value2  Random value3
0              3              7
1              9              2
2              4              3
3              2              5

In [23]:
df.loc[:,['Random value2','Random value3']]

   Random value2  Random value3
0              3              7
1              9              2
2              4              3
3              2              5